/* ── Theme System — TigrãoImports Mostruário ── */

export const TEMAS = {
  tigrao: {
    nome: "Tigrão Clássico",
    descricao: "Laranja vibrante — identidade TigrãoImports",
    preview: "🐯",
    bg: "#FFFFFF", bgSecondary: "#F5F5F7", text: "#1D1D1F", textMuted: "#86868B",
    accent: "#E8740E", accentHover: "#D06A0D", accentLight: "#FFF5EB",
    cardBg: "#FFFFFF", cardBorder: "#E8E8ED",
    heroBg: "#0A0A0A", heroText: "#FFFFFF",
    btnComprar: "#34C759", btnComprarHover: "#2DB84D",
    headerBg: "rgba(255,255,255,0.8)",
  },
  dark: {
    nome: "Dark Premium",
    descricao: "Preto elegante — visual Apple Store",
    preview: "🖤",
    bg: "#0A0A0A", bgSecondary: "#141414", text: "#F5F5F5", textMuted: "#888888",
    accent: "#E8740E", accentHover: "#F5A623", accentLight: "#1E1208",
    cardBg: "#141414", cardBorder: "#2A2A2A",
    heroBg: "#141414", heroText: "#F5F5F5",
    btnComprar: "#34C759", btnComprarHover: "#2DB84D",
    headerBg: "rgba(10,10,10,0.8)",
  },
  clean: {
    nome: "Clean Minimalista",
    descricao: "Branco puro — foco total nos produtos",
    preview: "⚪",
    bg: "#FFFFFF", bgSecondary: "#FAFAFA", text: "#111111", textMuted: "#999999",
    accent: "#111111", accentHover: "#333333", accentLight: "#F5F5F5",
    cardBg: "#FFFFFF", cardBorder: "#EEEEEE",
    heroBg: "#111111", heroText: "#FFFFFF",
    btnComprar: "#111111", btnComprarHover: "#333333",
    headerBg: "rgba(255,255,255,0.9)",
  },
  neon: {
    nome: "Neon Moderno",
    descricao: "Verde neon — visual tech futurista",
    preview: "💚",
    bg: "#0D0D0D", bgSecondary: "#1A1A1A", text: "#E0E0E0", textMuted: "#777777",
    accent: "#00FF88", accentHover: "#00CC6A", accentLight: "#0D2618",
    cardBg: "#1A1A1A", cardBorder: "#2D2D2D",
    heroBg: "#0D0D0D", heroText: "#FFFFFF",
    btnComprar: "#00FF88", btnComprarHover: "#00CC6A",
    headerBg: "rgba(13,13,13,0.9)",
  },
  luxury: {
    nome: "Luxury Gold",
    descricao: "Dourado com preto — premium exclusivo",
    preview: "✨",
    bg: "#0C0C0C", bgSecondary: "#161616", text: "#F0E6D3", textMuted: "#8B7D6B",
    accent: "#C9A84C", accentHover: "#D4B65E", accentLight: "#1A1608",
    cardBg: "#161616", cardBorder: "#2A2418",
    heroBg: "#0C0C0C", heroText: "#F0E6D3",
    btnComprar: "#C9A84C", btnComprarHover: "#D4B65E",
    headerBg: "rgba(12,12,12,0.9)",
  },
  ocean: {
    nome: "Ocean Blue",
    descricao: "Azul oceano — tranquilo e confiável",
    preview: "🌊",
    bg: "#F8FBFF", bgSecondary: "#EDF4FF", text: "#1A2744", textMuted: "#6B7D99",
    accent: "#0071E3", accentHover: "#0060C0", accentLight: "#E8F2FF",
    cardBg: "#FFFFFF", cardBorder: "#D4E3F5",
    heroBg: "#0A1628", heroText: "#FFFFFF",
    btnComprar: "#0071E3", btnComprarHover: "#0060C0",
    headerBg: "rgba(248,251,255,0.9)",
  },
  // ── Tendências 2026 ──
  capri: {
    nome: "Capri Blue",
    descricao: "Azul Capri vibrante — tendência global 2026",
    preview: "💎",
    bg: "#FFFFFF", bgSecondary: "#F0F6FF", text: "#0F1B2D", textMuted: "#5A6E85",
    accent: "#0066CC", accentHover: "#0055AA", accentLight: "#E5F0FF",
    cardBg: "#FFFFFF", cardBorder: "#C8D9ED",
    heroBg: "#0066CC", heroText: "#FFFFFF",
    btnComprar: "#0066CC", btnComprarHover: "#0055AA",
    headerBg: "rgba(255,255,255,0.9)",
  },
  cocoa: {
    nome: "Cocoa Premium",
    descricao: "Marrom cacau sofisticado — tendência 2026",
    preview: "🍫",
    bg: "#FAF7F4", bgSecondary: "#F0EBE5", text: "#2C1810", textMuted: "#7A6B5D",
    accent: "#6B3A2A", accentHover: "#7D4635", accentLight: "#F5EDE8",
    cardBg: "#FFFFFF", cardBorder: "#E0D5CA",
    heroBg: "#2C1810", heroText: "#F5EDE8",
    btnComprar: "#6B3A2A", btnComprarHover: "#7D4635",
    headerBg: "rgba(250,247,244,0.9)",
  },
  forest: {
    nome: "Forest Green",
    descricao: "Verde floresta — design biofílico natural",
    preview: "🌿",
    bg: "#F5F8F5", bgSecondary: "#EBF1EB", text: "#1A2E1A", textMuted: "#5C755C",
    accent: "#2D6A2D", accentHover: "#3A7D3A", accentLight: "#E5F0E5",
    cardBg: "#FFFFFF", cardBorder: "#C8DAC8",
    heroBg: "#1A2E1A", heroText: "#E5F0E5",
    btnComprar: "#2D6A2D", btnComprarHover: "#3A7D3A",
    headerBg: "rgba(245,248,245,0.9)",
  },
  rosegold: {
    nome: "Rose Gold",
    descricao: "Rosa dourado — elegância feminina premium",
    preview: "🌸",
    bg: "#0E0A0C", bgSecondary: "#1A1416", text: "#F5E8ED", textMuted: "#9E8892",
    accent: "#D4937A", accentHover: "#E0A58E", accentLight: "#1E1215",
    cardBg: "#1A1416", cardBorder: "#2E2428",
    heroBg: "#0E0A0C", heroText: "#F5E8ED",
    btnComprar: "#D4937A", btnComprarHover: "#E0A58E",
    headerBg: "rgba(14,10,12,0.9)",
  },
  midnight: {
    nome: "Midnight Navy",
    descricao: "Azul marinho noturno — sofisticado e sério",
    preview: "🌙",
    bg: "#0B1120", bgSecondary: "#121B2E", text: "#E4E9F2", textMuted: "#7B8BA5",
    accent: "#4A90D9", accentHover: "#5DA0E9", accentLight: "#14203A",
    cardBg: "#121B2E", cardBorder: "#1E2D48",
    heroBg: "#0B1120", heroText: "#E4E9F2",
    btnComprar: "#4A90D9", btnComprarHover: "#5DA0E9",
    headerBg: "rgba(11,17,32,0.9)",
  },
  sunset: {
    nome: "Sunset Warm",
    descricao: "Tons quentes de pôr do sol — acolhedor",
    preview: "🌅",
    bg: "#FFFBF7", bgSecondary: "#FFF3E8", text: "#2D1B0E", textMuted: "#8B7060",
    accent: "#E85D3A", accentHover: "#D44E2D", accentLight: "#FFF0EB",
    cardBg: "#FFFFFF", cardBorder: "#F0D4C4",
    heroBg: "#E85D3A", heroText: "#FFFFFF",
    btnComprar: "#E85D3A", btnComprarHover: "#D44E2D",
    headerBg: "rgba(255,251,247,0.9)",
  },
  arctic: {
    nome: "Arctic Ice",
    descricao: "Branco gelo com azul claro — clean e fresco",
    preview: "🧊",
    bg: "#F5F9FC", bgSecondary: "#EAF2F8", text: "#1C2938", textMuted: "#6B8299",
    accent: "#3AAFE8", accentHover: "#2A9ED6", accentLight: "#E8F5FC",
    cardBg: "#FFFFFF", cardBorder: "#D0E4F2",
    heroBg: "#1C2938", heroText: "#FFFFFF",
    btnComprar: "#3AAFE8", btnComprarHover: "#2A9ED6",
    headerBg: "rgba(245,249,252,0.9)",
  },
  carbon: {
    nome: "Carbon Sport",
    descricao: "Cinza carbono esportivo — masculino e forte",
    preview: "🏎️",
    bg: "#111111", bgSecondary: "#1A1A1A", text: "#EAEAEA", textMuted: "#808080",
    accent: "#E63946", accentHover: "#FF4D5A", accentLight: "#1E0C0E",
    cardBg: "#1A1A1A", cardBorder: "#2E2E2E",
    heroBg: "#111111", heroText: "#EAEAEA",
    btnComprar: "#E63946", btnComprarHover: "#FF4D5A",
    headerBg: "rgba(17,17,17,0.9)",
  },
  emerald: {
    nome: "Emerald Luxe",
    descricao: "Verde esmeralda com dourado — joalheria premium",
    preview: "💎",
    bg: "#060D08", bgSecondary: "#0D1A10", text: "#E8F0EA", textMuted: "#7A9B80",
    accent: "#50C878", accentHover: "#63D68A", accentLight: "#0D2015",
    cardBg: "#0D1A10", cardBorder: "#1A3020",
    heroBg: "#060D08", heroText: "#E8F0EA",
    btnComprar: "#50C878", btnComprarHover: "#63D68A",
    headerBg: "rgba(6,13,8,0.9)",
  },
  cherry: {
    nome: "Cherry Red",
    descricao: "Vermelho cereja intenso — ousado e marcante",
    preview: "🍒",
    bg: "#FFFAF9", bgSecondary: "#FFF0ED", text: "#2D0F0A", textMuted: "#8B5A50",
    accent: "#C41E3A", accentHover: "#A8192F", accentLight: "#FFE8E5",
    cardBg: "#FFFFFF", cardBorder: "#F0C4BD",
    heroBg: "#C41E3A", heroText: "#FFFFFF",
    btnComprar: "#C41E3A", btnComprarHover: "#A8192F",
    headerBg: "rgba(255,250,249,0.9)",
  },
  lavender: {
    nome: "Lavender Soft",
    descricao: "Lavanda suave — calmo e moderno",
    preview: "💜",
    bg: "#FAF8FF", bgSecondary: "#F0ECFF", text: "#1E1533", textMuted: "#7B6E99",
    accent: "#7C5CFC", accentHover: "#6A48E8", accentLight: "#EDE8FF",
    cardBg: "#FFFFFF", cardBorder: "#D8D0F0",
    heroBg: "#1E1533", heroText: "#F0ECFF",
    btnComprar: "#7C5CFC", btnComprarHover: "#6A48E8",
    headerBg: "rgba(250,248,255,0.9)",
  },
  amazon: {
    nome: "Marketplace",
    descricao: "Inspirado nos grandes marketplaces — direto e funcional",
    preview: "📦",
    bg: "#FFFFFF", bgSecondary: "#F3F3F3", text: "#0F1111", textMuted: "#565959",
    accent: "#FF9900", accentHover: "#E88B00", accentLight: "#FFF5E0",
    cardBg: "#FFFFFF", cardBorder: "#D5D9D9",
    heroBg: "#232F3E", heroText: "#FFFFFF",
    btnComprar: "#FFD814", btnComprarHover: "#F7CA00",
    headerBg: "rgba(35,47,62,0.95)",
  },
} as const;

export type TemaKey = keyof typeof TEMAS;
export type Tema = (typeof TEMAS)[TemaKey];

export function getTema(key: string | null | undefined): Tema {
  if (key && key in TEMAS) return TEMAS[key as TemaKey];
  return TEMAS.tigrao;
}

export function getTemaKey(key: string | null | undefined): TemaKey {
  if (key && key in TEMAS) return key as TemaKey;
  return "tigrao";
}

/** All theme keys in display order */
export const TEMA_KEYS: TemaKey[] = [
  "tigrao", "dark", "clean", "ocean", "luxury", "neon",
  "capri", "cocoa", "forest", "rosegold", "midnight", "sunset",
  "arctic", "carbon", "emerald", "cherry", "lavender", "amazon",
];

/** CSS custom properties object for a given theme — use as `style` on root div */
export function temaCSSVars(tema: Tema): Record<string, string> {
  return {
    "--t-bg": tema.bg,
    "--t-bg2": tema.bgSecondary,
    "--t-text": tema.text,
    "--t-muted": tema.textMuted,
    "--t-accent": tema.accent,
    "--t-accent-hover": tema.accentHover,
    "--t-accent-light": tema.accentLight,
    "--t-card-bg": tema.cardBg,
    "--t-card-border": tema.cardBorder,
    "--t-hero-bg": tema.heroBg,
    "--t-hero-text": tema.heroText,
    "--t-btn": tema.btnComprar,
    "--t-btn-hover": tema.btnComprarHover,
    "--t-header-bg": tema.headerBg,
  };
}
